[tools]
"aqua:charmbracelet/glow" = "latest"
bat = "latest"
bun = "latest"
codex = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:googleworkspace/cli" = "latest"
"github:unhappychoice/splashboard" = "2.10.1"
herdr = "latest"
lazygit = "latest"
node = "25.2.1"
ollama = "0.18.3"
ripgrep = "latest"
rust = "stable"
rust-analyzer = "latest"
yazi = "latest"
zoxide = "latest"
